version: "3.9"
   
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   env_file:
  #     - ./postgres/.env
  db:
    image: mysql:latest
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    expose: 
      - "3306"
    volumes:
      - ./data/db:/var/lib/minesql
  web:
    build: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: ./django/web
        target: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    env_file:
      - ./django/.env
      - ./elasticsearch/.env
  elasticsearch:
    image: elasticsearch:6.8.15
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

