version: "3.9"
   
services:
  postgres:
    image: postgres:13.2-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./mysql/.env
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: django
    volumes:
      - type: bind
        source: ./django/web
        target: /code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - postgres
      - elasticsearch
    env_file:
      - ./django/.env
      - ./elasticsearch/.env
  elasticsearch:
    image: elasticsearch:6.8.15
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

